[project]
name = "umwelt-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo[recommended]>=0.19.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
